"""
Digest generator — produces the ultra-compressed GitHub Issue body.

Daily digest: ~500 tokens total (vs ~25,000 for raw data).
Weekly digest: ~1,200 tokens total, includes search intelligence + top comments.

This is the ONLY thing Claude ever sees. No raw posts. No noise.
"""

from datetime import datetime, timezone

_CATEGORY_EMOJI = {
    "ai_claude":        "🤖",
    "personal_branding": "💼",
    "vc_funding":        "💰",
    "cybersecurity":     "🔐",
}

_TYPE_ICON = {
    "ANNOUNCEMENT": "📢",
    "CVE":          "🚨",
    "DISCUSSION":   "💬",
    "TUTORIAL":     "📖",
    "MEME":         "🔥",
    "INSIGHT":      "📊",
    "GENERAL":      "📌",
}

_CATEGORY_LABEL = {
    "ai_claude":         "AI & Claude",
    "personal_branding": "Personal Branding",
    "vc_funding":        "VC & Funding",
    "cybersecurity":     "Cybersecurity",
}


def _type_icon(content_type: str) -> str:
    return _TYPE_ICON.get(content_type, "📌")


# ---------------------------------------------------------------------------
# Daily digest
# ---------------------------------------------------------------------------

def generate_daily_digest(category_posts: dict[str, list[dict]], date: str) -> str:
    """
    Generate a markdown digest for GitHub Issues from scored, filtered posts.
    category_posts: {category_key: [scored_post, ...]}
    """
    lines = [
        f"# Reddit Daily Digest — {date}",
        "",
        "> Auto-generated by reddit-intelligence pipeline. "
        "Paste into Claude with: *\"Write me 3 LinkedIn posts from this digest.\"*",
        "",
    ]

    total_posts = sum(len(p) for p in category_posts.values())
    lines.append(f"**{total_posts} signal posts** across {len(category_posts)} categories | "
                 f"Scores = live upvotes at time of scrape")
    lines.append("")
    lines.append("---")

    for category, posts in category_posts.items():
        if not posts:
            continue

        emoji = _CATEGORY_EMOJI.get(category, "📌")
        label = _CATEGORY_LABEL.get(category, category.replace("_", " ").title())
        lines.append(f"\n## {emoji} {label}\n")

        for post in posts:
            icon = _type_icon(post.get("content_type", "GENERAL"))
            score = post.get("score", 0)
            comments = post.get("num_comments", 0)
            title = post.get("title", "")
            angle = post.get("linkedin_angle", "")
            url = post.get("permalink") or post.get("url", "")
            eng = post.get("engagement_score", 0)

            lines += [
                f"### {icon} {title}",
                f"**{score:,} upvotes · {comments:,} comments** · "
                f"Engagement score: `{eng}` · Type: `{post.get('content_type', '')}`",
                f"**LinkedIn Angle:** {angle}",
                f"**Source:** {url}",
                "",
            ]

    lines += [
        "---",
        f"*Pipeline: Composio Reddit API · "
        f"Generated {datetime.now(timezone.utc).strftime('%H:%M UTC')}*",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Weekly digest
# ---------------------------------------------------------------------------

def generate_weekly_digest(
    category_posts: dict[str, list[dict]],
    search_results: dict[str, dict[str, list[dict]]],
    week_ending: str,
) -> str:
    """
    Generate a weekly deep-research digest for GitHub Issues.
    search_results: {category: {query: [posts]}}
    """
    lines = [
        f"# Reddit Weekly Research — Week ending {week_ending}",
        "",
        "> Deep research digest. Includes top posts, top comments, and search intelligence.",
        "> Use this to plan your **LinkedIn content calendar for the week**.",
        "",
        "---",
    ]

    # --- Section 1: Top posts with comments ---
    lines.append("\n## Top Posts This Week\n")

    for category, posts in category_posts.items():
        if not posts:
            continue
        emoji = _CATEGORY_EMOJI.get(category, "📌")
        label = _CATEGORY_LABEL.get(category, category.replace("_", " ").title())
        lines.append(f"### {emoji} {label}\n")

        for post in posts:
            icon = _type_icon(post.get("content_type", "GENERAL"))
            score = post.get("score", 0)
            n_comments = post.get("num_comments", 0)
            title = post.get("title", "")
            angle = post.get("linkedin_angle", "")
            url = post.get("permalink") or post.get("url", "")
            top_comments = post.get("comments", [])

            lines += [
                f"#### {icon} {title}",
                f"**{score:,} upvotes · {n_comments:,} comments** · "
                f"Type: `{post.get('content_type', '')}`",
                f"**Angle:** {angle}",
                f"**Source:** {url}",
            ]

            if top_comments:
                lines.append("\n**Top community voices:**")
                for c in top_comments[:3]:
                    excerpt = c[:150].rstrip()
                    if len(c) > 150:
                        excerpt += "…"
                    lines.append(f"> *\"{excerpt}\"*")

            lines.append("")

    # --- Section 2: Search intelligence ---
    has_search = any(
        queries for queries in search_results.values()
        if any(posts for posts in queries.values())
    )

    if has_search:
        lines += [
            "---",
            "\n## Search Intelligence",
            "",
            "*Targeted search finds intent-rich discussions that don't always rank as top posts.*",
            "",
        ]

        for category, queries in search_results.items():
            if not queries:
                continue
            emoji = _CATEGORY_EMOJI.get(category, "📌")
            label = _CATEGORY_LABEL.get(category, category.replace("_", " ").title())
            lines.append(f"### {emoji} {label} — Search Hits\n")

            for query, posts in queries.items():
                if not posts:
                    continue
                lines.append(f"**Query:** `{query}`")
                for post in posts:
                    score = post.get("score", 0)
                    url = post.get("permalink") or post.get("url", "")
                    lines.append(f"- **{post.get('title', '')}** ({score:,} pts) — {url}")
                lines.append("")

    lines += [
        "---",
        f"*Pipeline: Composio Reddit API · "
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
    ]

    return "\n".join(lines)
